builds:
- main: ./cmd/chart-scanner
  binary: ./chart-scanner
  env:
  - CGO_ENABLED=0
  ldflags:
  - -w -X main.version={{.Version}} -X main.revision={{.ShortCommit}}
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64

archive:
  format: tar.gz
  files:
  - LICENSE
