version: '1.0'
stages:
- build
- release
steps:
  BuildDockerImage:
    title: Build Docker image
    stage: build
    type: build
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
  PushDockerImage:
    title: Push Docker image (latest)
    stage: release
    type: push
    candidate: ${{BuildDockerImage}}
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    registry: dockerhub
