# Note: must set env var GITHUB_TOKEN for goreleaser
version: '1.0'
stages:
- build
- release
steps:
  BuildDockerImage:
    title: Build Docker image
    stage: build
    type: build
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
  UploadReleaseArtifacts:
    title: Upload release artifacts
    stage: release
    image: goreleaser/goreleaser:v0.95.0
    working_directory: /go/src/github.com/${{CF_REPO_OWNER}}
    commands:
    - ln -s /codefresh/volume/${{CF_REPO_NAME}} ${{CF_REPO_NAME}} && cd ${{CF_REPO_NAME}}
    - git checkout tags/${{CF_BRANCH_TAG_NORMALIZED}}
    - goreleaser --rm-dist
  PushDockerImageTagged:
    title: Push Docker image (tag)
    stage: release
    type: push
    candidate: ${{BuildDockerImage}}
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}
    registry: dockerhub
